config/routes.rb
Rails.application.routes.draw do
  resources :breeds

  root "breeds#index"

  resources :breeds, only: [:index, :show]

end

app/models/breed.rb
class Breed < ActiveRecord::Base
  validates_presence_of :name, :pic_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController

  def index
    @breeds = DogBreedFetcher.fetch_breeds
  end

  def show
    @breed = DogBreedFetcher.fetch(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/views/breeds/index.html.erb
<div class="dog">

  <h1>Click On the breed to see images</h1>

  <table>
  <% @breeds.each do |breed| %>
      <tr>
        <td>
          <a href="<%= breed_path(id: breed)  %>"><%= breed %></a>
        </td>
      </tr>
  <% end %>

  </table>

</div>

app/views/breeds/show.html.erb
<div class="dog">

  <h1>It's a dog</h1>



  <h3><%= @breed.name.humanize %></h3>

  <%= image_tag @breed.pic_url %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTestProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>